### ISSUE TITLE
trouble to connect with python

### ISSUE THREAD

**Issue by AfcEagle** [DcodingTheWeb/ProxAllium#10]
hi and thanks for great app
im using proxalium for telegram desktop and its GREAT

since 2 month am tring to use proxalium socks proxy with PYTHON3 and TELETHON but it can connect to proxaliumSocks

the code for proxy is:
    proxy = (socks.SOCKS5 ,"127.0.0.1" ,9050 )
    client = TelegramClient("XXX", api_id, api_hash ,proxy=proxy)

tested different kind of proxy like
"127.0.0.1:9050"
"127.0.0.1:9150"
"localhost:9050"
"localhost:9150"

please guid me to use proxaliumSocks in python3
thanks

**Comment by TheDcoder** [comment]
Hi, you're most welcome, always good to hear feedback directly from the users :grinning: 

About your question, unfortunately I am not very familiar with the python library you are using, so the best course of action for you is to get in contact with the authors of the library if you aren't getting any errors from your code. You can also check Tor's output to see if it is giving you any error messages.

Aside from that generic advice I cannot help you very much with python, sorry about that. Feel free to post any other Tor or ProxAllium related questions and I will answer them. Best of luck with your code! :+1:

**Comment by AfcEagle** [comment]
thank you for answer

**Comment by AfcEagle** [comment]
i found some one that had this problem and solved
this is python bug
in python version 3.8 just add this code 
```
import asyncio
asyncio.set_event_loop(asyncio.SelectorEventLoop())
```
solving problem

[topic link](https://github.com/LonamiWebs/Telethon/issues/1337#issuecomment-560490965)

thank you for your support TheDcoder
