### ISSUE TITLE
Add HiDPI display support (if possible/factible and/or worth it at all)

### ISSUE THREAD

**Issue by xp499** [DcodingTheWeb/ProxAllium#14]
Hello, i've tested the app on a HiDPI monitor and main window as Tor console output window shows somewhat blurry although Windows tries its best at scaling non-HiDPI supported apps.

App was tested on a Lenovo Legion 5 Pro with an integrated screen of 2560x1600 resolution at a 16:10 screen ratio + 150% of Windows native scaling, enabled and configured by factory defaults.

**Comment by xp499** [comment]
Didn't tested on a 4K display, but probably scale it worse, and looks and read even more blurry. Idrk but may guess that from my experience.

**Comment by TheDcoder** [comment]
Due to how the GUI is designed, it doesn't scale properly if I set DPI-awareness:
![image](https://user-images.githubusercontent.com/6347576/132110689-95c121b4-b378-4c0e-b20b-4492f6e2c35d.png)

Perhaps there is a way to disable scaling to not make it look blurry but it would also make the window smaller physically as the pixel density is higher :worried:

**Comment by xp499** [comment]
> Perhaps there is a way to disable scaling to not make it look blurry but it would also make the window smaller physically as the pixel density is higher 😟

That's the point of HiDPI density screens, but then is windows which should be in charge of handling the scale and multiplicate/(or) dividide scaled pixels by well-known fixed values for each resolution. 4K resolution is called like that because it is normally configured to combine 4 pixels to show as one vs 1080p. At least that's how i understand it.

**Comment by TheDcoder** [comment]
I have decided not to add support for HiDPI displays as adding proper support takes a rework of the GUI, which I am not ready to do.

I investigated the alternative solution of disabling scaling but that doesn't seem to be very easy either, and even if I can implement it, users with large displays would have a hard time seeing the small text.

So even if it is blurry at the moment, it is still usable and that's more important, it's not like you need to look at it every day :wink:

Closing this issue, at-least for now.
