### ISSUE TITLE
Add support for app being available at Chocolatey Package Manager repo

### ISSUE THREAD

**Issue by xp499** [DcodingTheWeb/ProxAllium#15]
Chocolatey Package Manager represents the opensource alternative for Microsoft Store front for opensource compliant apps.

Adding your app to this repo will surely expose to a new and wider audience of users among adding a new central and easy method of setup, distribution and update whenever it's any available.

If you will to expand your userbase, please consider checking this issue anytime you can.

P.D.: Notice that as related by Chocolatey pacman webpage, the recommended way to be installed is with Administrator privileges. This represents that each time you want to setup any other app with it, package manager should be executed with these same privileges.

P.D. 2: I share this setup along using the chocolateyGUI (a GUI for chocolatey CLI pacman) companion app, also executed with Admin privileges in order to setup any app with it without any problems.

**Comment by TheDcoder** [comment]
Thanks for the suggestion, I will look into it after the next release, which may come soon as I am fixing some of the other issues.

**Comment by xp499** [comment]
Np, thanks for taking this into further consideration.

**Comment by TheDcoder** [comment]
I created a "RFP" issue in the chocolatey community package requests repository: https://github.com/chocolatey-community/chocolatey-package-requests/issues/1062

Hopefully someone interested will pick it up and maintain it :)

**Comment by TheDcoder** [comment]
It's now available in the community repository! https://community.chocolatey.org/packages/proxallium

Thanks to @Cossey for adopting the package :+1:
