### ISSUE TITLE
Add a payment method on LiberayPay to enable support for donations to you and your projects (NOT RELATED TO PROXALLIUM)

### ISSUE THREAD

**Issue by xp499** [DcodingTheWeb/ProxAllium#16]
As stated in title desc.

Didn't know how to directly contact or communicate this issue to you, so i opened a new one related to this subject just here.

Sorry if it's not appropiate.

You can close it anytime, anyways.

It was just a communication for you to notice this.

**Comment by xp499** [comment]
![liberapay](https://user-images.githubusercontent.com/15360416/131486706-a3148e1a-82f5-44e0-a385-727a1e84e589.png)

**Comment by TheDcoder** [comment]
No issues, thanks for bringing this to my attention! I will look into it :smile:

**Comment by TheDcoder** [comment]
I think the issue was I only had Stripe connected with only one currency (which is not the Euro), I have now connected my PayPal account too.

@xp499 Can you check again if you are still getting the same error? Thanks.

**Comment by xp499** [comment]
I assumed it was possible in the first place because liberapay had a choice between 24 different currencies.

Seems like working now, gonna donate that quantity. Greetings and thanks for your time, effort and work.

**Comment by TheDcoder** [comment]
> I assumed it was possible in the first place because liberapay had a choice between 24 different currencies.

The admin interface for Liberapay has a different section where I can configure which currencies I can receive, I selected all options, but I didn't realize Stripe didn't support them. Hopefully PayPal should work.


> Seems like working now, gonna donate that quantity. Greetings and thanks for your time, effort and work.

Thank you very much! I appreciate your support :)

**Comment by xp499** [comment]
You should have received the donation by now, @TheDcoder

A confirmation would be nice, to know that everything worked as intended.

Cheers.

**Comment by TheDcoder** [comment]
@xp499 I got the email from PayPal, thank you for the contribution!

**Comment by xp499** [comment]
Nice to hear that. Thank you for the confirmation.
