### ISSUE TITLE
Add ability to minimize to task bar instead of tray

### ISSUE THREAD

**Issue by TheDcoder** [DcodingTheWeb/ProxAllium#17]
> Can you tell me why you want ProxAllium to be minimized to the taskbar? It does't do much so in my opinion it is better if it is hidden away in the tray.

Because i need to have opened and minimized console Tor Output window in the taskbar to check what's the current status of Tor binary.

Debug, warns and info console messages do not show up in main window log and minimize to system tray's behaviour it is also affecting to that window when you try to minimize it. That, under my point of view, or needs, should be optional behaviour as when you minimize console Tor Output window it just dissapear and/or minimize also to system tray icon where there's no easy nor trivial way to restore it in one click if you have/want to have/need to have application's icon tray hidden inside Window's system tray overflow menu.

It is nice to have "Start minimized" option and the application's system tray icon as a reminder that the app is running in the background but you may understand that there's also people needs' that also match working with the app at foreground while still also need to minimize it and restore it from the taskbar in one click regardless of app's icon tray.

On another example: Stopping or starting Tor manually whenever it is needed to or wanted to while having system app icon try hidden on the overflow menu. Restore window it does not take just one click also in this case.

_Originally posted by @xp499 in https://github.com/DcodingTheWeb/ProxAllium/issues/4#issuecomment-907189076_

**Comment by TheDcoder** [comment]
I changed the behavior in 0bc38c294fb42628a0e7d9d685520996d60cdb6c to make the windows not hide when minimizing, instead they will be hidden to tray only when closed.

This is simpler than adding an extra option to change the behavior, I don't think it matters much to make it configurable.

@xp499 Thanks for suggesting the idea, I didn't realize the auto-hide behavior was limiting the ways in which the user can use ProxAllium :)

**Comment by xp499** [comment]
> 
> 
> I changed the behavior in [0bc38c2](https://github.com/DcodingTheWeb/ProxAllium/commit/0bc38c294fb42628a0e7d9d685520996d60cdb6c) to make the windows not hide when minimizing, instead they will be hidden to tray only when closed.
> 
> This is simpler than adding an extra option to change the behavior, I don't think it matters much to make it configurable.
> 
> @xp499 Thanks for suggesting the idea, I didn't realize the auto-hide behavior was limiting the ways in which the user can use ProxAllium :)

Np, glad to help.

Yeah that's even smarter approach that the one i was trying to explain. Didn't thought on it.

Anyways it is hard for me to express myself on english, as you can see, i'm a non-native person who tries to communicate using it.

Sorry for not being that precise on my description, and thank you for interpretating correctly the functionality i wanted to trasmit to you in order to remaking it.

Greetings.
