### ISSUE TITLE
GET READY!! The new generation of Tor brings some new features

### ISSUE THREAD

**Issue by Ahmed0425** [DcodingTheWeb/ProxAllium#5]
Change log [here](https://blog.torproject.org/tor-0329-released-we-have-new-stable-series)
If you read the change log carefully you will notice some new interesting features, for example
1. Tor now has an option to be used as an HTTP proxy
2. some command line options were removed (as it's unsafe) or added

The change log is very big but I think there are very few features that require changes in AutoIt code and the previous features are the major ones
you will need to either build tor from source or wait until the pre-built binary build is available on the official site

**Comment by TheDcoder** [comment]
Very interesting indeed. I will have a look at the change log and see if any changes are breaking compatibility with ProxAllium.

I use official builds from the website, so I will wait for the release of a new version of Tor Browser which will hopefully happen before the end of this month.

As for the new feature of being able to use Tor as an HTTP proxy, I will have to make some arrangements in ProxAllium to support it.

**Comment by Ahmed0425** [comment]
Great! I'll try to build tor using visual studio 2010 as this seems to be much easier than mingw then I'll upload it in another comment so you may have much time to test it then release it immediately even before the new official build
I expect this to be done by today or tomorrow at most as downloading visual studio takes much time already
EDIT
The tutorial I found is outdated (2014) and I couldn't compile tor -_- sorry about that :(

**Comment by TheDcoder** [comment]
Good luck! Visual Studio is a pain to download, it's large and very heavy for my laptop.

I will try building using MinGW but I currently do not have a proper build environment. Maybe in the future I will build Tor to ship with ProxAllium :)

**Comment by TheDcoder** [comment]
Tor Browser with the 0.3.2.x stable series was released today, I grabbed the Tor build and tried it with ProxAllium, due to a change in how the version is displayed in `tor --version` it broke ProxAllium's version detection code, I need to patch this and build a special hot-fix version of ProxAllium, only then it can work with the latest version.
<hr>

Output from 0.3.1.9:
```
E:\Projects\AutoIt\ProxAllium\Builds\v0.3-beta\ProxAllium\Tor>tor.exe --version
Tor version 0.3.1.9 (git-727d3f1b5e6eeda7).
```

Output from 0.3.2.9:
```
E:\Software\ProxAllium\Tor>tor.exe --version
Tor version 0.3.2.9.
```

**Comment by TheDcoder** [comment]
I patched ProxAllium to deal with version strings without the truncated git hash in 927dfa8bb9e3cccddf836d401b4e38214549e6ac. I will release the patched build of v0.3 with the latest version of Tor in a few hours (hopefully).

**Comment by TheDcoder** [comment]
I have created a new branch called `v0.3-beta_hotfix` and cherry-picked the commit above, changes look like they are pretty good so far, I will start the build process.

**Comment by TheDcoder** [comment]
All done! The hotfix release is up for download now, head over to the website and get it 😀

**Comment by TheDcoder** [comment]
I finally managed to add support (b8da7b4974d18d052cd26b87924c69fa790fb095) for the HTTP tunnel!

I never thought I would get this busy with work and life. I have some important decisions to make related to this project, but I must tend to the remaining task and release a new version as soon as possible 😄
