### ISSUE TITLE
"New Tor circuit" option

### ISSUE THREAD

**Issue by leafcutterant** [DcodingTheWeb/ProxAllium#6]
This feature may be familiar from the Tor Browser. It would be great to be able to switch to a new circuit with the click of a button on the UI. This could be also added to the right-click menu of the tray icon.

**Comment by TheDcoder** [comment]
Thanks for the suggestion, I will look into it.

**Comment by TheDcoder** [comment]
Looks like it is very easy to do using the Tor controller's [`SIGNAL NEWNYM`](https://github.com/torproject/torspec/blob/6bd0a699a0856240480a4bc339722db142beec0a/control-spec.txt#L446) command:
```
NEWNYM    -- Switch to clean circuits, so new application requests
                   don't share any circuits with old ones.  Also clears
                   the client-side DNS cache.  (Tor MAY rate-limit its
                   response to this signal.)
```

I will add an option for this in the GUI 😄

**Comment by TheDcoder** [comment]
All done! I added the option in 6c2427c648036a472eebee680bfad3c0053470ec, here is a screenshot for your viewing pleasure:
![autoit3_2018-02-07_09-56-38](https://user-images.githubusercontent.com/6347576/35898558-4613bad6-0bed-11e8-9855-c25393c7f640.png)

**Comment by leafcutterant** [comment]
Thank you, a pleasure! Looking forward to the next release.

**Comment by TheDcoder** [comment]
I need to work on supporting the HTTP proxy feature which was introduced in Tor 0.3.2.x and also #4 before releasing v0.4

Let me know if you are interested in beta testing the latest development version, you can reach me by [IRC](https://proxallium.org/chat) or by my email (shown on my profile page) 😄
